### Particle Image Function
### Version: 1.0.4
### Width: 8
### Height: 8
### ParticleType: dust

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

particle dust{color:[0.910,0.110,0.910],scale:1} ^-0.25 ^0 ^0 0 0 0 0 1 force @a
particle dust{color:[0.372,0.105,0.870],scale:1} ^0.125 ^0 ^0 0 0 0 0 1 force @a
